# .github/workflows/hello.yml
name: Hello World

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment?"
        required: true
        default: "dev"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Learning GitHub Actions in ${{ github.event.inputs.environment }}!"
# on: workflow_dispatch

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print message
#         run: echo "Learning GitHub Actions !"


# ## push event
# on:
#   push:
#     branches:
#       - main
#       - develop
#     paths:
#       - 'src/**'

